### PR TITLE
add nerdcommenter

### PR DESCRIPTION
**Pull request by caseywatts**
Have you ever wanted a keystroke to comment out the line(s) you're working with? [NERDCommenter](https://github.com/scrooloose/nerdcommenter) is a super easy way to do it.

`git clone https://github.com/scrooloose/nerdcommenter.git ~/.vim/bundle/nerdcommenter`

example use:
- visually select a block of text (in `.erb` or `.rb` or `.html` or most anything)
- `,c[space]` toggles the lines - commenting them out or putting them back (depending on whether the first line is commented out)

mnemonics:
- `,c` is the namespace for NERDCommenter.
- `[space]` is a toggle for a lot of things, like play/pause.

It's also the 9th most used VIM plugin according to http://vimawesome.com/ ^_~

Should this be added to our dotfiles? Pros/cons?

### CODE REVIEW

**Comment by benjaminoakes** [comment]
Worst change ever!  :-1:  :trollface: 

(This sounds cool, though.)

Do you do `,c<space>` to toggle?

**Comment by caseywatts** [comment]
@benjaminoakes exactly! ;D

**Comment by alexgraffeocohen** [comment]
I've wanted something like this for ages; yes please!

**Comment by caseywatts** [comment]
the janus-vim plugin suite had it bound to `[cmd]/` which I think is is common in other text editors. I like that keybinding but I'm not sure it'll work for us. I think this default makes sense~

**Comment by danbernier** [comment]
I'm not sure this feature is worth the extra plug-in. I don't usually forget which language I'm writing in, or have trouble typing.

But it's worth a try.

**Comment by caseywatts** [comment]
@danbernier do you think it might it be better to add a set of custom `.vimrc` aliases to achieve the same sort of effects?

`.rb` and `.html` are definitely straightforward to comment out. I'm not sure how I'd smartly write aliases to remove comments, or to be file-language aware in a nice way, or to comment out `.erb` tags. I think the plugin has probably done a better job with those than I would, and it's also much more mature than any code I'd write.

**Comment by alexgraffeocohen** [comment]
Yeah I was going to say, if it handles commenting out ERB blocks well it's worth it for that alone probably.

**Comment by danbernier** [comment]
@caseywatts nah, I think I'd rather have the plug-in then rely on a ton of `.vimrc` stuff.

**Comment by jnimety** [comment]
I'm curious, what's wrong with: `visual block select the first column`, `I`, `<comment character>`?

**Comment by danbernier** [comment]
Html and erb comments.
On May 3, 2015 10:28 AM, "Joel Nimety" notifications@github.com wrote:

> I'm curious, what's wrong with: visual block select the first column, I, <comment
> character>?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ContinuityControl/dotfiles/pull/12#issuecomment-98488219
> .

## 

## 

---

This email and all files transmitted with it are intended solely for use by 
the intended recipient.  Any other use is prohibited.  If you received this 
email in error, please notify the sender, delete the email and destroy all 
attachments.  Opinions and ideas expressed herein are solely those of the 
sender, and may not reflect the official position of Continuity.

**Comment by ZachBeta** [comment]
+1 to `.erb` commenting being the biggest value prop I'm concerned about.
Visual block commenting is pretty intuitive to me and doesn't add another command to my brain.

**Comment by tlball** [comment]
Maybe I’m just lazy, but I like having to know only one command to comment/uncomment no matter what type of file I’m in.

> On May 4, 2015, at 10:07 AM, Zach Morek notifications@github.com wrote:
> 
> +1 to .erb commenting being the biggest value prop I'm concerned about.
> Visual block commenting is pretty intuitive to me and doesn't add another command to my brain.
> 
> —
> Reply to this email directly or view it on GitHub https://github.com/ContinuityControl/dotfiles/pull/12#issuecomment-98742822.

## 

## 

---

This email and all files transmitted with it are intended solely for use by 
the intended recipient.  Any other use is prohibited.  If you received this 
email in error, please notify the sender, delete the email and destroy all 
attachments.  Opinions and ideas expressed herein are solely those of the 
sender, and may not reflect the official position of Continuity.

**Comment by jnimety** [comment]
ok, I see the value of this for .erb files but before merging please ask yourself how often you need block commenting in erb and if the weight of another plugin is worth it.

**Comment by caseywatts** [comment]
I'd estimate the weight of adding this vim plugin is minimal. I might be missing something?
- insignificant expected maintenance time (for a well-maintained/mature plugin like this one)
- insignificant impact on vim loading time/speed/memory-consumption
- insignificant impact on anyone who would like to ignore this addition

There is a potentially significant impact on anyone who adopts this plugin - they can comment out slightly easier, spend less time thinking about typing and more about code. It would also affect developer happiness if it brings anyone joy to use this (that might be short-lived as we get used to it).

On an arbitrary scale of 0-10 for positive/negative impact I might estimate:
- Negative Impact: 0/10
- Positive Impact: 2/10

Worth it? :)

**Comment by jnimety** [comment]
I'm ok either way, I just want to make sure we get reasonable value from the plugins we add.

**Comment by danbernier** [comment]
Even with a common set of dotfiles, we have to admit that we will all have
different work styles and vim styles. I have had this feature in other
environments, and use it maybe half the time, but that's me. If others are
excited for this, I'm ok with it. Either way, I see tiny impact.
On May 4, 2015 1:55 PM, "Joel Nimety" notifications@github.com wrote:

> I'm ok either way, I just want to make sure we get reasonable value from
> the plugins we add.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ContinuityControl/dotfiles/pull/12#issuecomment-98796409
> .

## 

## 

---

This email and all files transmitted with it are intended solely for use by 
the intended recipient.  Any other use is prohibited.  If you received this 
email in error, please notify the sender, delete the email and destroy all 
attachments.  Opinions and ideas expressed herein are solely those of the 
sender, and may not reflect the official position of Continuity.

**Comment by caseywatts** [comment]
Merged in via command line directly to master (I forgot I could use the github merge pull request button!)

**Comment by danbernier** [comment]
That's ok, I think we generally prefer git flow to the github merge button.
On May 5, 2015 3:19 PM, "Casey Watts" notifications@github.com wrote:

> Merged in via command line directly to master (I forgot I could use the
> github merge pull request button!)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ContinuityControl/dotfiles/pull/12#issuecomment-99190243
> .

## 

## 

---

This email and all files transmitted with it are intended solely for use by 
the intended recipient.  Any other use is prohibited.  If you received this 
email in error, please notify the sender, delete the email and destroy all 
attachments.  Opinions and ideas expressed herein are solely those of the 
sender, and may not reflect the official position of Continuity.

**Comment by jnimety** [comment]
but not for dotfiles :)

On Tue, May 5, 2015 at 3:52 PM, Dan Bernier notifications@github.com
wrote:

> That's ok, I think we generally prefer git flow to the github merge button.
> On May 5, 2015 3:19 PM, "Casey Watts" notifications@github.com wrote:
> 
> > Merged in via command line directly to master (I forgot I could use the
> > github merge pull request button!)
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/ContinuityControl/dotfiles/pull/12#issuecomment-99190243
> > 
> > .
> 
> ## 
> 
> ## 
> 
> ---
> 
> This email and all files transmitted with it are intended solely for use
> by
> the intended recipient. Any other use is prohibited. If you received this
> email in error, please notify the sender, delete the email and destroy all
> attachments. Opinions and ideas expressed herein are solely those of the
> sender, and may not reflect the official position of Continuity.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ContinuityControl/dotfiles/pull/12#issuecomment-99202020
> .

## 

Joel Nimety
Senior VP, Engineering
Continuity
203.285.8133 (office)
203.763.9263 (cell)
http://www.continuity.net
http://www.linkedin.com/in/jnimety

## 

## 

---

This email and all files transmitted with it are intended solely for use by 
the intended recipient.  Any other use is prohibited.  If you received this 
email in error, please notify the sender, delete the email and destroy all 
attachments.  Opinions and ideas expressed herein are solely those of the 
sender, and may not reflect the official position of Continuity.

**Pull request closed without merging**
