### PR TITLE
Move ruby classes in .bin to .bin-services

### PR DESCRIPTION
**Pull request by alexgraffeocohen**
I never liked that these files were in the .bin folder to begin with, so
this is probably good anyway. But I also want to do this so that there
can be new script files called "Feature" and "Hotfix" in the .bin
folder that load Thor CLIs.

Questions:
- Does anything else need to be done for a `.bin-services` folder to be automatically created in everyone's home folders?
- Do we want to change the name of the folder? Should I create a folder name that's more specific to creating stories with scripts in preparation for extracting a gem?

### CODE REVIEW

**Comment by jhirbour** [comment]
Yes I think you'd need to add a "if dir doesn't exist make it"... probably to the zsh.rc file. (and then after a month or 2 remove it).  Or maybe a setup script for the dot files... #randomThoughts

**Comment by alexgraffeocohen** [comment]
@jhirbour cool, I will look into that

**Comment by treznick** [comment]
https://github.com/technicalpickles/homesick#homesick_subdir

**Comment by alexgraffeocohen** [comment]
@treznick seems from the README I won't need homesick_subdir, since my new folder is directly is in `dotfiles/home`, not a subdirectory

**Comment by treznick** [comment]
then you're good!

On Tue, Dec 22, 2015 at 3:54 PM, Alex Wilkinson notifications@github.com
wrote:

> @treznick https://github.com/treznick seems from the README I won't
> need homesick_subdir, since my new folder is directly is in dotfiles/home,
> not a subdirectory
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ContinuityControl/dotfiles/pull/38#issuecomment-166727108
> .

## 

Tom Reznick
Software Engineer, Continuity
914-519-8966

## 

## 

---

This email and all files transmitted with it are intended solely for use by 
the intended recipient.  Any other use is prohibited.  If you received this 
email in error, please notify the sender, delete the email and destroy all 
attachments.  Opinions and ideas expressed herein are solely those of the 
sender, and may not reflect the official position of Continuity.

**Pull request merged**
