### PR TITLE
Push it!

### PR DESCRIPTION
**Pull request by treznick**
This PR adds the `git push-it` command, which is the same as running `git push origin $(git current-branch)`

This is kind of like nudge-it, except for pushing. It's nice when you want to push something up the first time to a branch (say for making a Pull Request. Hey! This is a Pull Request! And I used `git push-it` to push the commit to github! Self-referential example!)

Also, push it

push it real good
Push it real good

### CODE REVIEW

**Comment by alexgraffeocohen** [comment]
Maybe this could set upstream as well? There wouldn't be any consequences of re-setting the upstream of develop or master every time, right?

**Comment by treznick** [comment]
Not in the workflow that we use, but this also specifies origin as the pushable remote each time you call it. My sense is that this command should just be a shorthand for `git push origin CURRENT_BRANCH`, and not also set the upstream branch (just in case that's something that you want to specify otherwise)

**Comment by jnimety** [comment]
how is this different from `git push` or `gp`?

**Comment by treznick** [comment]
just noticed this comment. Short-answer: not much. `git push` will implicitly use the current branch and the current remote if the upstream branch is set, but it's a longhand thing to type the first time, and this makes the workflow of running, say, a bugfix very simple, e.g.:

```
create-hotfix "Fix this bug"
#write some code (if the last commit has a "finishes" before the story number, then this never needs to touch the browser except to put stories near release flags)
git push-it
git flow-rebase
git flow hotfix finish
```

**Comment by treznick** [comment]
FWIW I'm happy to revert the merge if we want to discuss this more. Apologies for an overly eager PR merge.

**Comment by jnimety** [comment]
there is a git setting to create the remote automatically.  Look at `man git-config`, search for `push.default`

We have this set to `simple`, `upstream` might give us the behavior you want.

**Comment by jnimety** [comment]
or maybe `current`.   this is located in `~/.gitconfig.d/shared`

**Comment by treznick** [comment]
will do!

**Comment by jnimety** [comment]
if `upstream` or `simple` works then we should revert

**Comment by danbernier** [comment]
Agreed - if we can lean on standard git, that's a :+1:

**Comment by treznick** [comment]
from my cursory investigation, it looks like `upstream` and `simple` don't automatically set the upstream branch. :/ 

THat said, if this also set the upstream branch, then it might be a more worthwhile shorthand:
`git push-it`
is considerably shorter than:
`git push -u origin $(git current-branch)`

Thoughts?

**Comment by treznick** [comment]
NB: I deleted `git push-it` on master

**Pull request merged**
