### PR TITLE
adjust colors for guard usability and better contrast for current tmux pane

### PR DESCRIPTION
**Pull request by jnimety**
screen shot 2015-05-05 at 11 53 22 am
screen shot 2015-05-05 at 11 54 29 am
screen shot 2015-05-05 at 11 55 28 am

### CODE REVIEW

**Comment by benjaminoakes** [comment]
:+1: 

Though I'll miss the green background...

**Comment by danbernier** [comment]
Not me! :sheep: it
On May 5, 2015 12:10 PM, "Ben Oakes" notifications@github.com wrote:

> [image: :+1:]
> 
> Though I'll miss the green background...
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ContinuityControl/dotfiles/pull/13#issuecomment-99127773
> .

## 

## 

---

This email and all files transmitted with it are intended solely for use by 
the intended recipient.  Any other use is prohibited.  If you received this 
email in error, please notify the sender, delete the email and destroy all 
attachments.  Opinions and ideas expressed herein are solely those of the 
sender, and may not reflect the official position of Continuity.

**Comment by caseywatts** [comment]
Do like :)

**Comment by jhirbour** [comment]
:shipit:

**Comment by alexgraffeocohen** [comment]
yes please

**Pull request merged**
