### PR TITLE
Use vim-plug to manage plugins

### PR DESCRIPTION
**Pull request by jnimety**
This is another PR asking for thoughts and feedback. I've seen a lot of vim plugins recommend or assume you're using vim-plug so I thought I'd see what that looks like for our dotfiles.

https://github.com/junegunn/vim-plug

Pros

- fewer git submodules to manage
- potentially easier management of per user plugins (can be added to `~/.vimrc.local` I think)
- easy plugin updates via `:PlugUpdate`
- configure individual plugins to load on demand (https://github.com/junegunn/vim-plug#on-demand-loading-of-plugins)

Cons

- no version synchronization between users
- not automatic; `:PlugInstall`/`PlugClean` required after modifying plugins / updating dotfiles

### CODE REVIEW

**Comment by benjaminoakes** [comment]
> no version synchronization between users

Does this mean the versions aren't deterministic?  I.e. I could pull on two machines and end up having one set of plugins on one machine and a different set on another?

**Comment by jnimety** [comment]
yes, it means you could have different versions of plugins across machines. I prefer to keep vim plugins up-to-date, so this isn't a problem for me.

**Comment by alexgraffeocohen** [comment]
> fewer git submodules to manage

This feels like the biggest pro to me! The submodules have always been the most confusing part of our setup, so I love the idea of moving away from that.

> no version synchronization between users

That's OK to me as well. You would just update more frequently, and as long as that's easy, then it's all good.

I think the only other con would be that we're adding a library to manage plugins. Part of the appeal to moving to vim's native package management, besides having user-specific plugins, was not needing an extra dependency for plugin management. But I have also seen `vim-plug` pop up a lot, so I don't have a problem, particularly if we get away from submodules!

**Comment by alexgraffeocohen** [comment]
I love the load on demand feature too. As invaluable as the vim plugins are, it would be great to get closer to vanilla vim boot time through some strategic on demand loading.

**Review by jhirbour — APPROVED** [review]
LGTM

**Comment by jnimety** [comment]
Added support for local plugins via `~/.vim/local/vimplug`, IMO this is the big win

**Comment by benjaminoakes** [comment]
Just set this up.  Seems to work well and install a lot faster than the submodules.  Thanks!

**Pull request merged**
