### PR TITLE
Update Submodules

### PR DESCRIPTION
**Pull request by alexgraffeocohen**
Happened to run a `git pull` from the vim bundle directory and received updates to all of our submodules. Doesn't look like anything has happened from the GitHub diff, but from local git there are new Subproject commit SHAs for each submodule folder.

### CODE REVIEW

**Review by treznick — APPROVED** [review]
Probably this is ok to merge. GH doesn't show any diffs on the submodules, which is odd. Also I wonder if we should have some sort of reminder to periodically do this.

**Comment by alexgraffeocohen** [comment]
@treznick yeah my best guess about GitHub not displaying changes is it has something to do with how they track submodules

**Comment by treznick** [comment]
@alexwilkinson are you able to confirm that your local diff contains actual changes in the submodules?

**Comment by benjaminoakes** [comment]
Has anyone besides @alexwilkinson tested this?  (If so, let's go ahead and merge.)

**Comment by alexgraffeocohen** [comment]
@treznick yeah can confirm that

**Comment by alexgraffeocohen** [comment]
screen shot 2017-02-05 at 1 01 52 pm
This is the sort of diff I'm seeing for I think all of the submodules @treznick

**Comment by treznick** [comment]
@alexwilkinson weirdness abounds even further then. Your screenshot shows a subproject commit for `ctrlp`, but looking at the remote listed in `.gitmodules` it show `https://github.com/kien/ctrlp.vim`, which has not been updated in years (and is currently unmaintained, btw). I'm not sure if this is the result of upstream changes then, because I'm hard pressed to find those changes. It may be the case that a `co -- .` will suffice.

**Comment by alexgraffeocohen** [comment]
@treznick Huh...well I guess this sounds a lot like the problem I mentioned in #68, maybe manifesting itself differently. Submodules are weird...

**Comment by benjaminoakes** [comment]
If you guys are both finding that it works, I think this is probably fine to merge.  (I just wanted to make sure it works on at least two people's machines.)

Aside: You can use a "patch" codefence to post diffs, which is handy sometimes:

```patch
  blah
+ added
- removed
```

A nice benefit of that is that it's searchable, unlike a screenshot.

**Comment by treznick** [comment]
honestly don't know if it's working. I'll leave that determination to @alexwilkinson. That said if it isn't it's a revert away

**Comment by treznick** [comment]
but that patch trick is a nice one @benjaminoakes

**Comment by benjaminoakes** [comment]
Well, reverting submodules can be weird, IIRC...

**Comment by alexgraffeocohen** [comment]
@jnimety ended up updating submodules in another merge so I'll close this one

**Pull request closed without merging**
