### PR TITLE
Add vim-mkdir

### PR DESCRIPTION
**Pull request by benjaminoakes**
From the README:

> ## Usage
> 
> ```
> :e this/does/not/exist/file.txt
> :w
> ```
> 
> Smile when you are not presented with an error. In stead, notice that
> vim has automatically created the non-existent directory for you.

### CODE REVIEW

**Comment by danbernier** [comment]
My only concern is that this'll create folders for typos: `app/modles/user.rb` I'm not sure that's a big deal. Thoughts?

**Comment by danbernier** [comment]
I guess I'm asking: @benjaminoakes, if you've run with this plug-in before, for a while, did you ever find that to be a problem?

**Comment by benjaminoakes** [comment]
I actually haven't run it for very long.  (Actually, this plugin was what initiated the slew of pull requests; committing some changes I had sitting around and updating against this upstream project made it much easier to manage adding the submodule.)

That said, I'm pretty sure it doesn't create the directories unless the file is written.  You'd have to open `app/modles/user.rb` and then save it to have `app/modles/` created by accident.

If you're good with that explanation, I'll resolve the merge conflict and we can move forward.

**Comment by danbernier** [comment]
Yeah, I see that. I was more hoping for an experience report of how it shakes out in practice. I'm guessing that, because I tab-complete paths, I'll only type a full path when it's a new folder, and that's when I'm paying careful attention anyway.

I think this is fine to merge (after merge conflicts are resolved). If practice shows it to be a pain, we can remove it.

**Comment by benjaminoakes** [comment]
Merge conflicts resolved.

**Comment by danbernier** [comment]
Thanks @benjaminoakes!

**Pull request merged**
