### PR TITLE
added gentle push because it's hard to remeber --force-with-lease

### PR DESCRIPTION
**Pull request by jhirbour**
I can never remember  --force-with-lease and use it all the time. So I made an alias .

Not sure if everyone would want this or not. I also don't feel strongly about the name... I'm open to suggestions. Naming is hard....

image

### CODE REVIEW

**Comment by ZachBeta** [comment]
A nice short name would be good.

Maybe `git nudge`

**Comment by benjaminoakes** [comment]
`gentle-push` doesn't sound quite right for something with `force` in the name.  I like `nudge` more because of that.

**Comment by jhirbour** [comment]
I've changed this to git nudge.

**Comment by tlball** [comment]
I'm good with this, however, for reference, you can tab complete --force-with-lease (because I can never remember it, either).

**Pull request merged**
