### PR TITLE
Gitignore tags in vim

### PR DESCRIPTION
**Pull request by treznick**

### CODE REVIEW

**Comment by danbernier** [comment]
Por que? What's this about?

**Comment by treznick** [comment]
https://andrew.stwrt.ca/posts/vim-ctags/

**Comment by danbernier** [comment]
Oh _those_ tags. Me gusta lo.

**Comment by danbernier** [comment]
Thx @treznick! :star2:

**Comment by treznick** [comment]
🍰

**Comment by danbernier** [comment]
MMMMM :cake:

**Pull request merged**
