### PR TITLE
Add better control and visibility over tmux windows

### PR DESCRIPTION
**Pull request by tlball**
I added a couple of tmux features I thought would be helpful. You shouldn't need to do anything other than update your dotfiles to get them to work.

Here are the features:
1. When you create a new tmux window, it will change the the directory you are on in your current window (helpful if you forget to cd to workspace/control in before creating your wemux)
2. When you delete a tmux window, your windows get renumbered so you don't have windows 0,1,4,5
3. Highlight current window title in status bar - the status bar is a bit different in color than before, but now the current window's title is highlighted. If you don't like the colors, they can be changed.

Let me know what you think!

### CODE REVIEW

**Comment by danbernier** [comment]
I really like these changes. I paired w/ @tlball today, and got to see them in action. :+1:

**Comment by jnimety** [comment]
I like these changes except for renumbering windows on delete.  When I have multiple windows open and I'm switching between them by number this would confuse me.

**Comment by treznick** [comment]
can this be overridden in a local zsh config? If so I say merge them! I'm
always, always, always bugged by gaps in numbers when I delete vim tabs,
and so I spend a ton of time trying to delete them in sequence, which is
crazy.

On Tue, Apr 28, 2015 at 9:19 AM, Joel Nimety notifications@github.com
wrote:

> I like these changes except for renumbering windows on delete. When I have
> multiple windows open and I'm switching between them by number this would
> confuse me.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ContinuityControl/dotfiles/pull/11#issuecomment-97060005
> .

## 

Tom Reznick
Junior Software Engineer, Continuity
914-519-8966

## 

## 

---

This email and all files transmitted with it are intended solely for use by 
the intended recipient.  Any other use is prohibited.  If you received this 
email in error, please notify the sender, delete the email and destroy all 
attachments.  Opinions and ideas expressed herein are solely those of the 
sender, and may not reflect the official position of Continuity.

**Comment by jnimety** [comment]
that is crazy.  How about opt-in for tab renumbering? -- J

On Tue, Apr 28, 2015 at 11:03 AM, Tom Reznick notifications@github.com
wrote:

> can this be overridden in a local zsh config? If so I say merge them! I'm
> always, always, always bugged by gaps in numbers when I delete vim tabs,
> and so I spend a ton of time trying to delete them in sequence, which is
> crazy.
> 
> On Tue, Apr 28, 2015 at 9:19 AM, Joel Nimety notifications@github.com
> wrote:
> 
> > I like these changes except for renumbering windows on delete. When I
> > have
> > multiple windows open and I'm switching between them by number this would
> > confuse me.
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/ContinuityControl/dotfiles/pull/11#issuecomment-97060005
> > 
> > .
> 
> ## 
> 
> Tom Reznick
> Junior Software Engineer, Continuity
> 914-519-8966
> 
> ## 
> 
> ## 
> 
> ---
> 
> This email and all files transmitted with it are intended solely for use
> by
> the intended recipient. Any other use is prohibited. If you received this
> email in error, please notify the sender, delete the email and destroy all
> attachments. Opinions and ideas expressed herein are solely those of the
> sender, and may not reflect the official position of Continuity.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub
> https://github.com/ContinuityControl/dotfiles/pull/11#issuecomment-97096790
> .

## 

Joel Nimety
Senior VP, Engineering
Continuity
203.285.8133 (office)
203.763.9263 (cell)
http://www.continuity.net
http://www.linkedin.com/in/jnimety

## 

## 

---

This email and all files transmitted with it are intended solely for use by 
the intended recipient.  Any other use is prohibited.  If you received this 
email in error, please notify the sender, delete the email and destroy all 
attachments.  Opinions and ideas expressed herein are solely those of the 
sender, and may not reflect the official position of Continuity.

**Comment by tlball** [comment]
So you can easily turn off the renumbering by commenting out ~/.tmux.conf:23 'set -g renumber-windows on’ or setting it to ‘off’.

I wonder if we could have custom, local tmux files that we can source in .tmux.conf to add in/overwrite settings we want. However, that would allow us to diverge too much from each other, and I think we want to be fairly consistent across each wemux.

Trish

> On Apr 28, 2015, at 10:08 AM, Joel Nimety notifications@github.com wrote:
> 
> that is crazy. How about opt-in for tab renumbering? -- J
> 
> On Tue, Apr 28, 2015 at 11:03 AM, Tom Reznick notifications@github.com
> wrote:
> 
> > can this be overridden in a local zsh config? If so I say merge them! I'm
> > always, always, always bugged by gaps in numbers when I delete vim tabs,
> > and so I spend a ton of time trying to delete them in sequence, which is
> > crazy.
> > 
> > On Tue, Apr 28, 2015 at 9:19 AM, Joel Nimety notifications@github.com
> > wrote:
> > 
> > > I like these changes except for renumbering windows on delete. When I
> > > have
> > > multiple windows open and I'm switching between them by number this would
> > > confuse me.
> > > 
> > > ## 
> > > 
> > > Reply to this email directly or view it on GitHub
> > > <
> > > https://github.com/ContinuityControl/dotfiles/pull/11#issuecomment-97060005
> > > 
> > > .
> > 
> > ## 
> > 
> > Tom Reznick
> > Junior Software Engineer, Continuity
> > 914-519-8966
> > 
> > ## 
> > 
> > ## 
> > 
> > ---
> > 
> > This email and all files transmitted with it are intended solely for use
> > by
> > the intended recipient. Any other use is prohibited. If you received this
> > email in error, please notify the sender, delete the email and destroy all
> > attachments. Opinions and ideas expressed herein are solely those of the
> > sender, and may not reflect the official position of Continuity.
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHub
> > https://github.com/ContinuityControl/dotfiles/pull/11#issuecomment-97096790
> > .
> 
> ## 
> 
> Joel Nimety
> Senior VP, Engineering
> Continuity
> 203.285.8133 (office)
> 203.763.9263 (cell)
> http://www.continuity.net
> http://www.linkedin.com/in/jnimety
> 
> ## 
> 
> ## 
> 
> ---
> 
> This email and all files transmitted with it are intended solely for use by 
> the intended recipient. Any other use is prohibited. If you received this 
> email in error, please notify the sender, delete the email and destroy all 
> attachments. Opinions and ideas expressed herein are solely those of the 
> sender, and may not reflect the official position of Continuity.
> —
> Reply to this email directly or view it on GitHub https://github.com/ContinuityControl/dotfiles/pull/11#issuecomment-97099850.

## 

## 

---

This email and all files transmitted with it are intended solely for use by 
the intended recipient.  Any other use is prohibited.  If you received this 
email in error, please notify the sender, delete the email and destroy all 
attachments.  Opinions and ideas expressed herein are solely those of the 
sender, and may not reflect the official position of Continuity.

**Comment by jnimety** [comment]
how a about a key binding to renumber tabs, so you can do it when you want?
-- J

On Tue, Apr 28, 2015 at 5:40 PM, Tricia Ball notifications@github.com
wrote:

> So you can easily turn off the renumbering by commenting out
> ~/.tmux.conf:23 'set -g renumber-windows on’ or setting it to ‘off’.
> 
> I wonder if we could have custom, local tmux files that we can source in
> .tmux.conf to add in/overwrite settings we want. However, that would allow
> us to diverge too much from each other, and I think we want to be fairly
> consistent across each wemux.
> 
> Trish
> 
> > On Apr 28, 2015, at 10:08 AM, Joel Nimety notifications@github.com
> > wrote:
> > 
> > that is crazy. How about opt-in for tab renumbering? -- J
> > 
> > On Tue, Apr 28, 2015 at 11:03 AM, Tom Reznick notifications@github.com
> > wrote:
> > 
> > > can this be overridden in a local zsh config? If so I say merge them!
> > > I'm
> > > always, always, always bugged by gaps in numbers when I delete vim
> > > tabs,
> > > and so I spend a ton of time trying to delete them in sequence, which
> > > is
> > > crazy.
> > > 
> > > On Tue, Apr 28, 2015 at 9:19 AM, Joel Nimety <notifications@github.com
> > > 
> > > wrote:
> > > 
> > > > I like these changes except for renumbering windows on delete. When I
> > > > have
> > > > multiple windows open and I'm switching between them by number this
> > > > would
> > > > confuse me.
> > > > 
> > > > ## 
> > > > 
> > > > Reply to this email directly or view it on GitHub
> > > > <
> > > 
> > > https://github.com/ContinuityControl/dotfiles/pull/11#issuecomment-97060005
> > > 
> > > > .
> > > 
> > > ## 
> > > 
> > > Tom Reznick
> > > Junior Software Engineer, Continuity
> > > 914-519-8966
> > > 
> > > ## 
> > > 
> > > ## 
> > > 
> > > ---
> > > 
> > > This email and all files transmitted with it are intended solely for
> > > use
> > > by
> > > the intended recipient. Any other use is prohibited. If you received
> > > this
> > > email in error, please notify the sender, delete the email and destroy
> > > all
> > > attachments. Opinions and ideas expressed herein are solely those of
> > > the
> > > sender, and may not reflect the official position of Continuity.
> > > 
> > > ## 
> > > 
> > > Reply to this email directly or view it on GitHub
> > > <
> > > https://github.com/ContinuityControl/dotfiles/pull/11#issuecomment-97096790
> > > 
> > > .
> > 
> > ## 
> > 
> > Joel Nimety
> > Senior VP, Engineering
> > Continuity
> > 203.285.8133 (office)
> > 203.763.9263 (cell)
> > http://www.continuity.net
> > http://www.linkedin.com/in/jnimety
> > 
> > ## 
> > 
> > ## 
> > 
> > ---
> > 
> > This email and all files transmitted with it are intended solely for use
> > by
> > the intended recipient. Any other use is prohibited. If you received
> > this
> > email in error, please notify the sender, delete the email and destroy
> > all
> > attachments. Opinions and ideas expressed herein are solely those of the
> > sender, and may not reflect the official position of Continuity.
> > —
> > Reply to this email directly or view it on GitHub <
> > https://github.com/ContinuityControl/dotfiles/pull/11#issuecomment-97099850
> > .
> 
> ## 
> 
> ## 
> 
> ---
> 
> This email and all files transmitted with it are intended solely for use
> by
> the intended recipient. Any other use is prohibited. If you received this
> email in error, please notify the sender, delete the email and destroy all
> attachments. Opinions and ideas expressed herein are solely those of the
> sender, and may not reflect the official position of Continuity.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ContinuityControl/dotfiles/pull/11#issuecomment-97227726
> .

## 

Joel Nimety
Senior VP, Engineering
Continuity
203.285.8133 (office)
203.763.9263 (cell)
http://www.continuity.net
http://www.linkedin.com/in/jnimety

## 

## 

---

This email and all files transmitted with it are intended solely for use by 
the intended recipient.  Any other use is prohibited.  If you received this 
email in error, please notify the sender, delete the email and destroy all 
attachments.  Opinions and ideas expressed herein are solely those of the 
sender, and may not reflect the official position of Continuity.

**Comment by danbernier** [comment]
I'd rather have a simple machine then a flexible one. Ie, decide to leave
the feature in or out, rather than configurable.
On Apr 28, 2015 5:53 PM, "Joel Nimety" notifications@github.com wrote:

> how a about a key binding to renumber tabs, so you can do it when you want?
> -- J
> 
> On Tue, Apr 28, 2015 at 5:40 PM, Tricia Ball notifications@github.com
> wrote:
> 
> > So you can easily turn off the renumbering by commenting out
> > ~/.tmux.conf:23 'set -g renumber-windows on’ or setting it to ‘off’.
> > 
> > I wonder if we could have custom, local tmux files that we can source in
> > .tmux.conf to add in/overwrite settings we want. However, that would
> > allow
> > us to diverge too much from each other, and I think we want to be fairly
> > consistent across each wemux.
> > 
> > Trish
> > 
> > > On Apr 28, 2015, at 10:08 AM, Joel Nimety notifications@github.com
> > > wrote:
> > > 
> > > that is crazy. How about opt-in for tab renumbering? -- J
> > > 
> > > On Tue, Apr 28, 2015 at 11:03 AM, Tom Reznick <
> > > notifications@github.com>
> > > wrote:
> > > 
> > > > can this be overridden in a local zsh config? If so I say merge them!
> > > > I'm
> > > > always, always, always bugged by gaps in numbers when I delete vim
> > > > tabs,
> > > > and so I spend a ton of time trying to delete them in sequence, which
> > > > is
> > > > crazy.
> > > > 
> > > > On Tue, Apr 28, 2015 at 9:19 AM, Joel Nimety <
> > > > notifications@github.com
> > > > 
> > > > wrote:
> > > > 
> > > > > I like these changes except for renumbering windows on delete.
> > > > > When I
> > > > > have
> > > > > multiple windows open and I'm switching between them by number this
> > > > > would
> > > > > confuse me.
> > > > > 
> > > > > ## 
> > > > > 
> > > > > Reply to this email directly or view it on GitHub
> > > > > <
> > 
> > https://github.com/ContinuityControl/dotfiles/pull/11#issuecomment-97060005
> > 
> > > > > .
> > > > 
> > > > ## 
> > > > 
> > > > Tom Reznick
> > > > Junior Software Engineer, Continuity
> > > > 914-519-8966
> > > > 
> > > > ## 
> > > > 
> > > > ## 
> > > > 
> > > > ---
> > > > 
> > > > This email and all files transmitted with it are intended solely for
> > > > use
> > > > by
> > > > the intended recipient. Any other use is prohibited. If you received
> > > > this
> > > > email in error, please notify the sender, delete the email and
> > > > destroy
> > > > all
> > > > attachments. Opinions and ideas expressed herein are solely those of
> > > > the
> > > > sender, and may not reflect the official position of Continuity.
> > > > 
> > > > ## 
> > > > 
> > > > Reply to this email directly or view it on GitHub
> > > > <
> > 
> > https://github.com/ContinuityControl/dotfiles/pull/11#issuecomment-97096790
> > 
> > > > .
> > > 
> > > ## 
> > > 
> > > Joel Nimety
> > > Senior VP, Engineering
> > > Continuity
> > > 203.285.8133 (office)
> > > 203.763.9263 (cell)
> > > http://www.continuity.net
> > > http://www.linkedin.com/in/jnimety
> > > 
> > > ## 
> > > 
> > > ## 
> > > 
> > > ---
> > > 
> > > This email and all files transmitted with it are intended solely for
> > > use
> > > by
> > > the intended recipient. Any other use is prohibited. If you received
> > > this
> > > email in error, please notify the sender, delete the email and destroy
> > > all
> > > attachments. Opinions and ideas expressed herein are solely those of
> > > the
> > > sender, and may not reflect the official position of Continuity.
> > > —
> > > Reply to this email directly or view it on GitHub <
> > 
> > https://github.com/ContinuityControl/dotfiles/pull/11#issuecomment-97099850
> > 
> > > .
> > 
> > ## 
> > 
> > ## 
> > 
> > ---
> > 
> > This email and all files transmitted with it are intended solely for use
> > by
> > the intended recipient. Any other use is prohibited. If you received this
> > email in error, please notify the sender, delete the email and destroy
> > all
> > attachments. Opinions and ideas expressed herein are solely those of the
> > sender, and may not reflect the official position of Continuity.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/ContinuityControl/dotfiles/pull/11#issuecomment-97227726
> > 
> > .
> 
> ## 
> 
> Joel Nimety
> Senior VP, Engineering
> Continuity
> 203.285.8133 (office)
> 203.763.9263 (cell)
> http://www.continuity.net
> http://www.linkedin.com/in/jnimety
> 
> ## 
> 
> ## 
> 
> ---
> 
> This email and all files transmitted with it are intended solely for use
> by
> the intended recipient. Any other use is prohibited. If you received this
> email in error, please notify the sender, delete the email and destroy all
> attachments. Opinions and ideas expressed herein are solely those of the
> sender, and may not reflect the official position of Continuity.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ContinuityControl/dotfiles/pull/11#issuecomment-97236666
> .

## 

## 

---

This email and all files transmitted with it are intended solely for use by 
the intended recipient.  Any other use is prohibited.  If you received this 
email in error, please notify the sender, delete the email and destroy all 
attachments.  Opinions and ideas expressed herein are solely those of the 
sender, and may not reflect the official position of Continuity.

**Comment by jnimety** [comment]
the feature is there, I'm only suggesting we add a key binding (if there isn't one already).  And generally, I agree for critical parts of our workflow.  In this case we're talking about numbering tabs.  Most of the time I don't want renumbering but maybe sometimes I do, so what's wrong with a key binding to renumber the tabs?

**Comment by tlball** [comment]
I’ll look to see if I can get a key binding to work, and then we can decide if we want to use them :).

Trish

> On Apr 29, 2015, at 8:14 AM, Joel Nimety notifications@github.com wrote:
> 
> the feature is there, I'm only suggesting we add a key binding (if there isn't one already). And generally, I agree for critical parts of our workflow. In this case we're talking about numbering tabs. Most of the time I don't want renumbering but maybe sometimes I do, so what's wrong with a key binding to renumber the tabs?
> 
> —
> Reply to this email directly or view it on GitHub https://github.com/ContinuityControl/dotfiles/pull/11#issuecomment-97422008.

## 

## 

---

This email and all files transmitted with it are intended solely for use by 
the intended recipient.  Any other use is prohibited.  If you received this 
email in error, please notify the sender, delete the email and destroy all 
attachments.  Opinions and ideas expressed herein are solely those of the 
sender, and may not reflect the official position of Continuity.

**Comment by danbernier** [comment]
I was arguing from principle, not specifics. If this is the place to flex
on the principle, that's fine.

On Wed, Apr 29, 2015 at 9:14 AM, Joel Nimety notifications@github.com
wrote:

> the feature is there, I'm only suggesting we add a key binding (if there
> isn't one already). And generally, I agree for critical parts of our
> workflow. In this case we're talking about numbering tabs. Most of the time
> I don't want renumbering but maybe sometimes I do, so what's wrong with a
> key binding to renumber the tabs?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ContinuityControl/dotfiles/pull/11#issuecomment-97422008
> .

## 

## 

---

This email and all files transmitted with it are intended solely for use by 
the intended recipient.  Any other use is prohibited.  If you received this 
email in error, please notify the sender, delete the email and destroy all 
attachments.  Opinions and ideas expressed herein are solely those of the 
sender, and may not reflect the official position of Continuity.

**Comment by tlball** [comment]
I added a key binding for renumbering. It will renumber by default. Use Ctrl+A Ctrl+n to turn
Renumbering OFF. Use Ctrl+A n to turn Renumbering ON.

I also added a key binding to the Right and Left arrows to allow you to traverse to the tmux windows, i.e. Ctrl+A Right takes you to the right window, and Ctrl+A Left takes you to the left window.

**Comment by jnimety** [comment]
Actually, I was hoping for a key binding to perform the renumbering. :)

If that's not possible let's just merge with renumbering on by default.

Sent from my iPhone

On Apr 29, 2015, at 6:13 PM, Tricia Ball notifications@github.com wrote:

I added a key binding for renumbering. It will renumber by default. Use
Ctrl+A Ctrl+n to turn
Renumbering OFF. Use Ctrl+A n to turn Renumbering ON.

I also added a key binding to the Right and Left arrows to allow you to
traverse to the tmux windows, i.e. Ctrl+A Right takes you to the right
window, and Ctrl+A Left takes you to the left window.

—
Reply to this email directly or view it on GitHub
https://github.com/ContinuityControl/dotfiles/pull/11#issuecomment-97603129
.

## 

## 

---

This email and all files transmitted with it are intended solely for use by 
the intended recipient.  Any other use is prohibited.  If you received this 
email in error, please notify the sender, delete the email and destroy all 
attachments.  Opinions and ideas expressed herein are solely those of the 
sender, and may not reflect the official position of Continuity.

**Comment by tlball** [comment]
Ha… totally misunderstood. I’ll look into it.

> On Apr 29, 2015, at 6:47 PM, Joel Nimety notifications@github.com wrote:
> 
> Actually, I was hoping for a key binding to perform the renumbering. :)
> 
> If that's not possible let's just merge with renumbering on by default.
> 
> Sent from my iPhone
> 
> On Apr 29, 2015, at 6:13 PM, Tricia Ball notifications@github.com wrote:
> 
> I added a key binding for renumbering. It will renumber by default. Use
> Ctrl+A Ctrl+n to turn
> Renumbering OFF. Use Ctrl+A n to turn Renumbering ON.
> 
> I also added a key binding to the Right and Left arrows to allow you to
> traverse to the tmux windows, i.e. Ctrl+A Right takes you to the right
> window, and Ctrl+A Left takes you to the left window.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ContinuityControl/dotfiles/pull/11#issuecomment-97603129
> .
> 
> ## 
> 
> ## 
> 
> ---
> 
> This email and all files transmitted with it are intended solely for use by 
> the intended recipient. Any other use is prohibited. If you received this 
> email in error, please notify the sender, delete the email and destroy all 
> attachments. Opinions and ideas expressed herein are solely those of the 
> sender, and may not reflect the official position of Continuity.
> —
> Reply to this email directly or view it on GitHub https://github.com/ContinuityControl/dotfiles/pull/11#issuecomment-97615573.

## 

## 

---

This email and all files transmitted with it are intended solely for use by 
the intended recipient.  Any other use is prohibited.  If you received this 
email in error, please notify the sender, delete the email and destroy all 
attachments.  Opinions and ideas expressed herein are solely those of the 
sender, and may not reflect the official position of Continuity.

**Comment by tlball** [comment]
Could not find way to key bind to renumbering windows, so I removed that commit.

**Pull request merged**
