### PR TITLE
Add command to open all modified but unstaged work in vim tabs

### PR DESCRIPTION
**Pull request by alexgraffeocohen**
Here is a cool command Dan, Tom, and I worked on together to open all of the files you have unstaged in separate vim tabs. A good use case for this would be if you are popping a stash, and you want to immediately open everything that was modified in the stash. (Also pairs well with git-gutter to see what happened in the files).

We cool with this?

### CODE REVIEW

**Comment by caseywatts** [comment]
I want to do this pretty often!

`vim -p` is a great trick, and `git show-files -m` is /also/ a great trick. I like this command :)

**Comment by tlball** [comment]
This looks cool. I'll have to remember to use it.
On May 8, 2015 2:28 PM, "Casey Watts" notifications@github.com wrote:

> I want to do this pretty often!
> 
> vim -p is a great trick, and git show-files -m is /also/ a great trick. I
> like this command :)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ContinuityControl/dotfiles/pull/15#issuecomment-100334042
> .

## 

## 

---

This email and all files transmitted with it are intended solely for use by 
the intended recipient.  Any other use is prohibited.  If you received this 
email in error, please notify the sender, delete the email and destroy all 
attachments.  Opinions and ideas expressed herein are solely those of the 
sender, and may not reflect the official position of Continuity.

**Comment by alexgraffeocohen** [comment]
Me too : ). I always forget commands like this. I think I'll pin a note for these kinds of things into slack.

**Comment by ZachBeta** [comment]
@benjaminoakes what's the command you were talking about in standup?

**Comment by alexgraffeocohen** [comment]
@benjaminoakes when you get a chance, could you post the command here or just a link to it? from what we discussed, we can probably just use that instead

**Comment by treznick** [comment]
Merge-able?

**Comment by alexgraffeocohen** [comment]
Yes, but @benjaminoakes has a more flexible version of this that could be plugged into RSpec as well. Could probably just merge this in anyways, not much harm.

**Comment by jhirbour** [comment]
:shipit:

**Comment by alexgraffeocohen** [comment]
committed on master

**Pull request closed without merging**
