### PR TITLE
Adds git wip commands

### PR DESCRIPTION
**Pull request by treznick**
This PR adds two commands:

`git wip-it`
and
`git unwip-it`

you know, for when a problem comes along

You must whip it

the first, adds _everything_ and commits it with this message `[skip ci] wip`

the second soft resets the second command and then resets again to unstage

The only thing I can think of that might make this better is if the second command would blow up if the most recent commit message didn't include the word wip

@jhirbour @benjaminoakes @danbernier @tlball @jnimety :eyeglasses: :thought_balloon: s?

### CODE REVIEW

**Comment by treznick** [comment]
`alias git-coolwhip=git-wip-it`

**Comment by benjaminoakes** [comment]
This is nice.  It would probably make sense to explain that "wip" stands for "work in progress" for people without the context.  I'd suggest a comment at the top of these two files.

**Comment by treznick** [comment]
can do!

**Comment by treznick** [comment]
cowboyed!

**Pull request merged**
