### PR TITLE
remove vim-gitgutter

### PR DESCRIPTION
**Pull request by caseywatts**
description of this plugin: https://github.com/airblade/vim-gitgutter

some pros:
- see diff-type information inline
- navigate between chunks of modified code

some cons:
- we're not used to seeing this sidebar; it's distracting

### CODE REVIEW

**Comment by benjaminoakes** [comment]
:+1:

I was one of the people who encouraged this to get merged originally.  I'm still for it, though I completely understand @alexwilkinson's concern about it making syntastic less visible.  If there's a middle ground, that could be nice.

I think it needs to be tried for a couple weeks to see if it adds value to our workflow.

Pros:
- You can jump into someone's Vim and see what they changed
- You can remember what you haven't committed more easily
- You can navigate in Vim by what's been changed according to Git 
- You can stage without leaving Vim via `,hs`, among other features

Cons:
- It uses the gutter (which reduces usable horizontal space)
- Syntastic is less visible

**Comment by jhirbour** [comment]
I like using it.

@tlball  and I found that on the mac adjusting the contrast in iterm makes the gutter bar contents way more visible (preferences => Profile => colors => Min contrast slider)

**Comment by alexgraffeocohen** [comment]
I will try playing with that contrast setting, since that was one of my key concerns!

**Comment by treznick** [comment]
not sure how to use this - doesn't seem to work on my pairing. Casey, maybe
you can show me when we next pair?

On Wed, Apr 22, 2015 at 2:19 PM, Alex Wilkinson notifications@github.com
wrote:

> I will try playing with that contrast setting, since that was one of my
> key concerns!
> 
> On Wed, Apr 22, 2015 at 11:46 AM, John Hirbour notifications@github.com
> wrote:
> 
> > I like using it.
> > @tlball and I found that on the mac adjusting the contrast in iterm
> > makes the gutter bar contents way more visible (preferences => Profile =>
> > 
> > ## colors => Min contrast slider)
> > 
> > Reply to this email directly or view it on GitHub:
> > 
> > https://github.com/ContinuityControl/dotfiles/pull/9#issuecomment-95242872
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ContinuityControl/dotfiles/pull/9#issuecomment-95290280
> .

## 

Tom Reznick
Junior Software Engineer, Continuity
914-519-8966

## 

## 

---

This email and all files transmitted with it are intended solely for use by 
the intended recipient.  Any other use is prohibited.  If you received this 
email in error, please notify the sender, delete the email and destroy all 
attachments.  Opinions and ideas expressed herein are solely those of the 
sender, and may not reflect the official position of Continuity.

**Comment by tlball** [comment]
I am a fan of it. It was one of the things I really missed from my IDE.
On Apr 22, 2015 1:26 PM, "Tom Reznick" notifications@github.com wrote:

> not sure how to use this - doesn't seem to work on my pairing. Casey, maybe
> you can show me when we next pair?
> 
> On Wed, Apr 22, 2015 at 2:19 PM, Alex Wilkinson notifications@github.com
> wrote:
> 
> > I will try playing with that contrast setting, since that was one of my
> > key concerns!
> > 
> > On Wed, Apr 22, 2015 at 11:46 AM, John Hirbour <notifications@github.com
> > 
> > wrote:
> > 
> > > I like using it.
> > > @tlball and I found that on the mac adjusting the contrast in iterm
> > > makes the gutter bar contents way more visible (preferences => Profile =>
> > > 
> > > ## colors => Min contrast slider)
> > > 
> > > Reply to this email directly or view it on GitHub:
> > 
> > https://github.com/ContinuityControl/dotfiles/pull/9#issuecomment-95242872
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/ContinuityControl/dotfiles/pull/9#issuecomment-95290280
> > 
> > .
> 
> ## 
> 
> Tom Reznick
> Junior Software Engineer, Continuity
> 914-519-8966
> 
> ## 
> 
> ## 
> 
> ---
> 
> This email and all files transmitted with it are intended solely for use
> by
> the intended recipient. Any other use is prohibited. If you received this
> email in error, please notify the sender, delete the email and destroy all
> attachments. Opinions and ideas expressed herein are solely those of the
> sender, and may not reflect the official position of Continuity.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ContinuityControl/dotfiles/pull/9#issuecomment-95292348
> .

## 

## 

---

This email and all files transmitted with it are intended solely for use by 
the intended recipient.  Any other use is prohibited.  If you received this 
email in error, please notify the sender, delete the email and destroy all 
attachments.  Opinions and ideas expressed herein are solely those of the 
sender, and may not reflect the official position of Continuity.

**Comment by danbernier** [comment]
I used it all today with only minor ill effects. (I'm still adjusting.)
On Apr 22, 2015 2:45 PM, "Tricia Ball" notifications@github.com wrote:

> I am a fan of it. It was one of the things I really missed from my IDE.
> On Apr 22, 2015 1:26 PM, "Tom Reznick" notifications@github.com wrote:
> 
> > not sure how to use this - doesn't seem to work on my pairing. Casey,
> > maybe
> > you can show me when we next pair?
> > 
> > On Wed, Apr 22, 2015 at 2:19 PM, Alex Wilkinson <
> > notifications@github.com>
> > wrote:
> > 
> > > I will try playing with that contrast setting, since that was one of my
> > > key concerns!
> > > 
> > > On Wed, Apr 22, 2015 at 11:46 AM, John Hirbour <
> > > notifications@github.com
> > > 
> > > wrote:
> > > 
> > > > I like using it.
> > > > @tlball and I found that on the mac adjusting the contrast in iterm
> > > > makes the gutter bar contents way more visible (preferences => Profile
> > > > =>
> > > > 
> > > > ## colors => Min contrast slider)
> > > > 
> > > > Reply to this email directly or view it on GitHub:
> > 
> > https://github.com/ContinuityControl/dotfiles/pull/9#issuecomment-95242872
> > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> > 
> > https://github.com/ContinuityControl/dotfiles/pull/9#issuecomment-95290280
> > 
> > > .
> > 
> > ## 
> > 
> > Tom Reznick
> > Junior Software Engineer, Continuity
> > 914-519-8966
> > 
> > ## 
> > 
> > ## 
> > 
> > ---
> > 
> > This email and all files transmitted with it are intended solely for use
> > by
> > the intended recipient. Any other use is prohibited. If you received this
> > email in error, please notify the sender, delete the email and destroy
> > all
> > attachments. Opinions and ideas expressed herein are solely those of the
> > sender, and may not reflect the official position of Continuity.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/ContinuityControl/dotfiles/pull/9#issuecomment-95292348
> > 
> > .
> 
> ## 
> 
> ## 
> 
> ---
> 
> This email and all files transmitted with it are intended solely for use
> by
> the intended recipient. Any other use is prohibited. If you received this
> email in error, please notify the sender, delete the email and destroy all
> attachments. Opinions and ideas expressed herein are solely those of the
> sender, and may not reflect the official position of Continuity.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ContinuityControl/dotfiles/pull/9#issuecomment-95298244
> .

## 

## 

---

This email and all files transmitted with it are intended solely for use by 
the intended recipient.  Any other use is prohibited.  If you received this 
email in error, please notify the sender, delete the email and destroy all 
attachments.  Opinions and ideas expressed herein are solely those of the 
sender, and may not reflect the official position of Continuity.

**Comment by jnimety** [comment]
My biggest objection with this is the interference with syntax checking feedback. Can we configure 2 gutters (one for git and one for syntax errors)?  Or make the gutter red on syntax errors?

Until we get this resolved I think we should remove it.

**Comment by jnimety** [comment]
answered my own question regarding multiple gutters: "Vim only allows one sign per line."

**Comment by jnimety** [comment]
@caseywatts let's revert until we get the compatibilities worked out.

**Comment by caseywatts** [comment]
@jnimety 
How can I see what the interference looks like? I'm not sure I've seen the two plugins conflict before.

**Comment by jnimety** [comment]
we've discussed the usability conflicts already.  With vim-gitgutter
installed it's hard to tell when there is a syntax error. To me, that's
more important than knowing what lines have changed (which I can get with
:Gdiff anyway) -- J

On Wed, Apr 29, 2015 at 10:32 AM, Casey Watts notifications@github.com
wrote:

> @jnimety https://github.com/jnimety
> How can I see what the interference looks like? I'm not sure I've seen the
> two plugins conflict before.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ContinuityControl/dotfiles/pull/9#issuecomment-97449497
> .

## 

Joel Nimety
Senior VP, Engineering
Continuity
203.285.8133 (office)
203.763.9263 (cell)
http://www.continuity.net
http://www.linkedin.com/in/jnimety

## 

## 

---

This email and all files transmitted with it are intended solely for use by 
the intended recipient.  Any other use is prohibited.  If you received this 
email in error, please notify the sender, delete the email and destroy all 
attachments.  Opinions and ideas expressed herein are solely those of the 
sender, and may not reflect the official position of Continuity.

**Comment by caseywatts** [comment]
We're on the same page that it can be removed from the team's dotfiles, I don't mind :)

I know usability conflicts have been brought up, but I haven't seen them myself. I still don't know what the conflict looks like or how it behaves.

I do find a lot of benefit from using this plugin. I'll definitely keep this in my personal server, and I think it's likely some other people on the team will want add it to theirs now that they've tried it. I think that's fine - I don't have any kind of strong urge to force the entire team to use this tool.

**Comment by caseywatts** [comment]
I've talked with Joel and Alex about reconciling the syntastic-visual-signal with gitgutter.

These three changes will help:
1. We can enable Syntastic's [statusline flag](https://github.com/scrooloose/syntastic) to put a red indicator on statusline (bottom right) when there is an error. (in `.vimrc`)
2. GitGutter has a less-obtrusive black background now (from a gitgutter update)
3. The gutter can always be open, so its use as a visual signal is minimized (in `.vimrc`)

**Comment by caseywatts** [comment]
added back in pull #14

**Pull request merged**
