### PR TITLE
Refactor Classes out of Git Flow Hotfix Script

### PR DESCRIPTION
**Pull request by alexgraffeocohen**
Besides it being nice that the script has a lot less going on now, this will set us up well for making a new script to make 0 point feature stories for both teams. Let us know if you have any feedback on the class names or the APIs of the classes or anything else.

### CODE REVIEW

**Comment by jhirbour** [comment]
:shipit:

**Comment by alexgraffeocohen** [comment]
@treznick made some changes along the lines of what you were suggesting by turning `StoryCreationUtils` into a `Hotfix` domain object that the script now just calls. I think it's a lot better now, and will merge by the end of the day.

**Comment by treznick** [comment]
did this get merged?

**Comment by treznick** [comment]
yes, yes it did

**Comment by treznick** [comment]
why thank you tom.

You're welcome other tom.

**Pull request closed without merging**
