### PR TITLE
Add git pull-all, which is a handy way to pull develop and master.

### PR DESCRIPTION
**Pull request by treznick**
This PR adds a command that I user a _lot_ to pull all of the things!

### CODE REVIEW

**Comment by treznick** [comment]
@jhirbour @benjaminoakes @danbernier @jnimety @tlball

**Comment by danbernier** [comment]
What, no stash?

**Comment by treznick** [comment]
Yes. No stash. The way I see this is that it pulls all the things. It's up to you to stash if necessary. I dunno, does stash seem like a good thing here?

**Comment by danbernier** [comment]
Yeah, IDK. Maybe it's fine w/o a stash.

**Comment by tlball** [comment]
I like it. I agree, no need to stash, users can manage that themselves.

**Comment by treznick** [comment]
merged!

**Pull request closed without merging**
