### PR TITLE
Add back gitgutter (with syntastic changes)

### PR DESCRIPTION
**Pull request by caseywatts**
from issue #9

### CODE REVIEW

**Comment by benjaminoakes** [comment]
This should have been a git module, right?

**Comment by caseywatts** [comment]
@benjaminoakes don't we use `pathogen`?

**Comment by caseywatts** [comment]
oh you mean a git submodule! ooh I think you're right

**Comment by benjaminoakes** [comment]
yeah, let's convert it so it's easier to update.

**Comment by jnimety** [comment]
@caseywatts can you switch this to a git submodule today?  It shouldn't take long.

**Comment by caseywatts** [comment]
yes

On Mon, May 18, 2015 at 9:13 AM, Joel Nimety notifications@github.com
wrote:

> @caseywatts https://github.com/caseywatts can you switch this to a git
> submodule today? It shouldn't take long.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ContinuityControl/dotfiles/pull/14#issuecomment-103054250
> .

## 

## 

---

This email and all files transmitted with it are intended solely for use by 
the intended recipient.  Any other use is prohibited.  If you received this 
email in error, please notify the sender, delete the email and destroy all 
attachments.  Opinions and ideas expressed herein are solely those of the 
sender, and may not reflect the official position of Continuity.

**Comment by caseywatts** [comment]
done! :)

On Mon, May 18, 2015 at 9:43 AM, Casey Watts cwatts@continuity.net wrote:

> yes
> 
> On Mon, May 18, 2015 at 9:13 AM, Joel Nimety notifications@github.com
> wrote:
> 
> > @caseywatts https://github.com/caseywatts can you switch this to a git
> > submodule today? It shouldn't take long.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/ContinuityControl/dotfiles/pull/14#issuecomment-103054250
> > .

## 

## 

---

This email and all files transmitted with it are intended solely for use by 
the intended recipient.  Any other use is prohibited.  If you received this 
email in error, please notify the sender, delete the email and destroy all 
attachments.  Opinions and ideas expressed herein are solely those of the 
sender, and may not reflect the official position of Continuity.

**Pull request merged**
