### PR TITLE
Stop tracking vim spell config

### PR DESCRIPTION
**Pull request by benjaminoakes**
A shared vim dictionary is unlikely to have a huge amount of value moving forward, so this is me making a motion to get rid of it.  I'm pretty sure that I'm the only one who ever committed changes to it anyway.  :smile:

**Fair warning:** this deletes the spellings you've collected, so that will have to be managed by individual users.  (I'm pretty sure there would be a warning/conflict if you have changes locally.)

### CODE REVIEW

**Comment by danbernier** [comment]
@benjaminoakes It's probably because I merged a few of your PRs, but this PR now has a merge conflict. Could you please rebase, & update here? I have no concerns about this PR otherwise. Thanks!

**Comment by benjaminoakes** [comment]
Will do.

**Comment by benjaminoakes** [comment]
Merge conflicts resolved.

**Comment by danbernier** [comment]
Thanks again @benjaminoakes!

**Pull request merged**
