### PR TITLE
Add Truecolor Support

### PR DESCRIPTION
**Pull request by jnimety**

### CODE REVIEW

**Comment by benjaminoakes** [comment]
> For terminals not supporting true colors, Solarized 8 will fall back to use an approximate palette based on xterm's 256 colors, which looks more or less like this:
>
> screenshot
> (Yeah, it looks like a different color scheme: Solarized palette is far away from xterm colors!)


Huh, that actually looks pretty different.

Do we have a sense of what terminals do/don't work with truecolor?

**Edit:** I'm probably okay with it either way, just wondering what the tradeoff is.

**Comment by PaulHayslett** [comment]
> Do we have a sense of what terminals do/don't work with truecolor?

https://gist.github.com/XVilka/8346728#terminals--true-color

Pretty much all modern emulators for Mac and Windows support truecolor now. The ones on the list that don't all look ancient and/or abandoned.

**Comment by jnimety** [comment]
If you'd like to test your terminal to see if truecolor is enabled, you can run this:
```
$ awk 'BEGIN{
    s="/\\/\\/\\/\\/\\"; s=s s s s s s s s;
    for (colnum = 0; colnum<77; colnum++) {
        r = 255-(colnum*255/76);
        g = (colnum*510/76);
        b = (colnum*255/76);
        if (g>255) g = 510-g;
        printf "\033[48;2;%d;%d;%dm", r,g,b;
        printf "\033[38;2;%d;%d;%dm", 255-r,255-g,255-b;
        printf "%s\033[0m", substr(s,colnum+1,1);
    }
    printf "\n";
}'
```
you should get a continuous color gradient:
Screen Shot 2020-01-25 at 10 14 05 AM

**Comment by benjaminoakes** [comment]
> If you'd like to test your terminal to see if truecolor is enabled, you can run this:

Very useful!  Seems fine on the one I was questioning (Chrome OS).

**Review by benjaminoakes — APPROVED** [review]

**Pull request merged**
